site_name: SpeechLine
repo_url: https://github.com/bookbot-kids/speechline
docs_dir: docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

extra_css:
  - css/extras.css

watch:
  - speechline

nav:
  - SpeechLine:
      - Home: index.md
      - Installation: INSTALLATION.md
      - Contributing: CONTRIBUTING.md
      - Project Charter: PROJECT_CHARTER.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - Guides:
      - Pipeline Explained: guides/pipeline.md
      - Running SpeechLine:
          - AWS SageMaker: guides/sagemaker.md
          - Google Cloud Engine: guides/google-cloud.md
  - API Reference:
      - Runner: reference/runner.md
      - Config: reference/config.md
      - Classifiers:
          - Wav2Vec2 Classifier: reference/classifiers/wav2vec2.md
      - Transcribers:
          - Wav2Vec2 Transcriber: reference/transcribers/wav2vec2.md
          - Whisper Transcriber: reference/transcribers/whisper.md
      - Base Modules:
          - Audio Classifier: reference/modules/audio_classifier.md
          - Audio Transcriber: reference/modules/audio_transcriber.md
          - Audio Module: reference/modules/audio_module.md
      - Pipelines:
          - Audio Classification with Padding: reference/pipelines/audio_classification_with_padding.md
      - Aligners:
          - Punctuation Forced Aligner: reference/aligners/punctuation_forced_aligner.md
      - Metrics:
          - Phoneme Error Rate: reference/metrics/phoneme_error_rate.md
      - Segmenters:
          - Audio Segmenter: reference/segmenters/segmenter.md
          - Silence Segmenter: reference/segmenters/silence_segmenter.md
          - Word Overlap Segmenter: reference/segmenters/word_overlap_segmenter.md
      - Utilities:
          - AirTable Interface: reference/utils/airtable.md
          - Dataset: reference/utils/dataset.md
          - Grapheme-to-Phoneme Converter: reference/utils/g2p.md
          - I/O: reference/utils/io.md
          - S3: reference/utils/s3.md
          - Word Tokenizer: reference/utils/tokenizer.md
      - Scripts:
          - aac-to-wav Audio Converter: reference/scripts/aac_to_wav.md
          - Audio Data Logger: reference/scripts/data_logger.md
          - Create HuggingFace Dataset: reference/scripts/create_hf_dataset.md
          - S3 Bucket Downloader: reference/scripts/download_s3_bucket.md
          - S3 Bucket Uploader: reference/scripts/upload_s3_bucket.md
