site_name: SpeechLine
repo_url: https://github.com/bookbot-kids/speechline
docs_dir: docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

extra_css:
  - css/extras.css

watch:
  - speechline

nav:
  - SpeechLine:
      - Home: index.md
      - Installation: INSTALLATION.md
      - Contributing: CONTRIBUTING.md
      - Project Charter: PROJECT_CHARTER.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - Examples:
      - Running SpeechLine:
          - AWS SageMaker: examples/sagemaker.md
  - API Reference:
      - Runner: reference/runner.md
      - Models:
          - Classifiers:
              - Wav2Vec2 Classifier: reference/models/classifiers/wav2vec2_classifier.md
          - Transcribers:
              - Wav2Vec2 Transcriber: reference/models/transcribers/wav2vec2_transcriber.md
              - Whisper Transcriber: reference/models/transcribers/whisper_transcriber.md
      - Base Modules:
          - Audio Classifier: reference/modules/audio_classifier.md
          - Audio Transcriber: reference/modules/audio_transcriber.md
          - Audio Module: reference/modules/audio_module.md
      - Utilities:
          - AirTable Interface: reference/utils/airtable.md
          - Audio Segmenter: reference/utils/segmenter.md
          - Config: reference/utils/config.md
          - Dataset: reference/utils/dataset.md
          - I/O: reference/utils/io.md
          - S3: reference/utils/s3.md
      - Scripts:
          - aac-to-wav Audio Converter: reference/scripts/aac_to_wav.md
          - Audio Data Logger: reference/scripts/data_logger.md
          - S3 Bucket Downloader: reference/scripts/download_s3_bucket.md
          - S3 Bucket Uploader: reference/scripts/upload_s3_bucket.md
