site_name: SpeechLine
repo_url: https://github.com/bookbot-kids/speechline
docs_dir: docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    # - navigation.expand
    - navigation.tabs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

watch:
  - speechline

nav:
  - Home: index.md
  - API Reference:
      - ML Models:
          - Audio Classifier: reference/ml/classifier.md
          - Audio Transcriber: reference/ml/transcriber.md
      - Base Classes:
          - Audio Dataset: reference/ml/dataset.md
          - Audio Module: reference/ml/module.md
      - Utils:
          - aac-to-wav Audio Converter: reference/utils/aac_to_wav.md
          - AirTable Interface: reference/utils/airtable.md
          - Audio Data Logger: reference/utils/data_logger.md
          - Audio Segmenter: reference/utils/segmenter.md
          - I/O: reference/utils/io.md
          - S3: reference/utils/s3.md
