[tox]
minversion = 3.8.0
envlist = python3.10
isolated_build = true

[gh-actions]
python =
    3.10: python3.10, flake8

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_test.txt
commands =
    coverage erase
    coverage run --branch -m pytest
    coverage report
    coverage xml -i -o coverage.xml
    flake8 speechline tests

[flake8]
extend-ignore = E203, E402, W293, W292, W291, W391, E501, E302, E305, E117, E128, E129, E202, F541, F401, F841, F821, E722
max-line-length = 88

[isort]
profile = black

[coverage:run]
source=speechline

[coverage:report]
exclude_lines =
    if __name__ == .__main__.: