name: Test documentation builds on Pull Requests

on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mkdocs-material mkdocstrings mkdocstrings-python-legacy
      - name: Install package
        run: pip install .
      - name: Build docs
        run: mkdocs build
